### 🧾 1. REGISTRO DE USUARIO (CREA USUARIO EN FIREBASE)
POST http://127.0.0.1:8001/api/registro/
Content-Type: application/json

{
  "email": "adios@test.com",
  "password": "123456",
  "rol": "sensor"
}

###

### 🔐 2. LOGIN (OBTENER TOKEN FIREBASE)
POST http://127.0.0.1:8001/api/login/
Content-Type: application/json

{
  "email": "adios@test.com",
  "password": "123456"
}

###

### 📥 3. INGESTA SIN ANOMALIA
POST http://127.0.0.1:8001/api/telemetria/ingesta/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwZmM5YzU0YjhiMjQyMWZmMTgyOTgxNTQyZmQ0NjRlOWJlYzM1NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGVsZW1ldHJpYS04NzEwMyIsImF1ZCI6InRlbGVtZXRyaWEtODcxMDMiLCJhdXRoX3RpbWUiOjE3NzYxODUyMDMsInVzZXJfaWQiOiJYanMwc3gwTVBqVmVacWpObUl5dkZqS3g1Q3cxIiwic3ViIjoiWGpzMHN4ME1QalZlWnFqTm1JeXZGakt4NUN3MSIsImlhdCI6MTc3NjE4NTIwMywiZXhwIjoxNzc2MTg4ODAzLCJlbWFpbCI6ImFkaW9zQHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkaW9zQHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.TlYxmAWxDGej7UlFsaA0tqf3p1CdtVE82y18lLfDQDbKPxXOHu6OUQoRUUGl4CIYcNiRLxXHyOJ5sjhEg27M8lIRrLENCJIwsX7OukMGgYJK-qcJMHH5bWjLMnqzX7hEb21w9u2DSp40VcgB07xP36QwCQdB3eP1xRCogXFt5BWtUohUP16_ijfdBXlMWa45oMIBSUuR-GjwCWHwtp7eu4c5rZObvZInKhVBAfqe9TbYklnWIBwS9pRTyW7V0OXiZ2Tp6WY-swZDRqG73sbjQRlkUoYVYoHQZnn03Gqnn8niQTAeWwz4OTN30IcGui2nsB9umfLnLT5TBSBgUbZOTg
Content-Type: application/json

{
  "id_servidor": "SRV-01",
  "cpu": 50,
  "ram": 40,
  "temperatura": 30
}

###

### 🚨 4. INGESTA CON ANOMALIA (DISPARA WEBSOCKET)
POST http://127.0.0.1:8001/api/telemetria/ingesta/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwZmM5YzU0YjhiMjQyMWZmMTgyOTgxNTQyZmQ0NjRlOWJlYzM1NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGVsZW1ldHJpYS04NzEwMyIsImF1ZCI6InRlbGVtZXRyaWEtODcxMDMiLCJhdXRoX3RpbWUiOjE3NzYxODUyMDMsInVzZXJfaWQiOiJYanMwc3gwTVBqVmVacWpObUl5dkZqS3g1Q3cxIiwic3ViIjoiWGpzMHN4ME1QalZlWnFqTm1JeXZGakt4NUN3MSIsImlhdCI6MTc3NjE4NTIwMywiZXhwIjoxNzc2MTg4ODAzLCJlbWFpbCI6ImFkaW9zQHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkaW9zQHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.TlYxmAWxDGej7UlFsaA0tqf3p1CdtVE82y18lLfDQDbKPxXOHu6OUQoRUUGl4CIYcNiRLxXHyOJ5sjhEg27M8lIRrLENCJIwsX7OukMGgYJK-qcJMHH5bWjLMnqzX7hEb21w9u2DSp40VcgB07xP36QwCQdB3eP1xRCogXFt5BWtUohUP16_ijfdBXlMWa45oMIBSUuR-GjwCWHwtp7eu4c5rZObvZInKhVBAfqe9TbYklnWIBwS9pRTyW7V0OXiZ2Tp6WY-swZDRqG73sbjQRlkUoYVYoHQZnn03Gqnn8niQTAeWwz4OTN30IcGui2nsB9umfLnLT5TBSBgUbZOTg
Content-Type: application/json

{
  "id_servidor": "SRV-01",
  "cpu": 95,
  "ram": 60,
  "temperatura": 80
}

###

### 📊 5. REPORTE ANALITICO
GET http://127.0.0.1:8001/api/telemetria/reporte/SRV-01/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwZmM5YzU0YjhiMjQyMWZmMTgyOTgxNTQyZmQ0NjRlOWJlYzM1NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGVsZW1ldHJpYS04NzEwMyIsImF1ZCI6InRlbGVtZXRyaWEtODcxMDMiLCJhdXRoX3RpbWUiOjE3NzYxODQ2NDQsInVzZXJfaWQiOiI3SHNmRVJMb2x6YldZRTZmQ09GajRoRVViYjgyIiwic3ViIjoiN0hzZkVSTG9semJXWUU2ZkNPRmo0aEVVYmI4MiIsImlhdCI6MTc3NjE4NDY0NCwiZXhwIjoxNzc2MTg4MjQ0LCJlbWFpbCI6ImhvbGFAdGVzdC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaG9sYUB0ZXN0LmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.EgOVzeOVQ5oCeDR-Wo0DiyxNNR0YMHNH7dymm7-EpWVR5H3j1nsppk5Eg6JvBwYuGXEO6oxBjea6LOVCQjYG1yb03N9ipFw9O9Jn1bi9Y5uCEJrUvJyyQx--EmyVJMa4vhdvUXHanH_Fe_I4nkUdi8Pyk7wNGLHw_4-HPtLwa7QyEaA18j_t8m7p6OitTi159A7BTG4XdQcvk3ETKPSfuN4zOaHGdyal94ccojliTp76QkWhufzNb9Y-j1GvLb2acs70TtgsG_zyimHJzEDYILuaYblUMAtl1-jeLu_OLEQs08VH9ErceZOMEEiUYBSGwlSOwpg4Lt7NZpaX2JwDLg

###

### 🖥️ 6. ESTADO ACTUAL
GET http://127.0.0.1:8001/api/telemetria/estado-actual/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjcwZmM5YzU0YjhiMjQyMWZmMTgyOTgxNTQyZmQ0NjRlOWJlYzM1NDUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdGVsZW1ldHJpYS04NzEwMyIsImF1ZCI6InRlbGVtZXRyaWEtODcxMDMiLCJhdXRoX3RpbWUiOjE3NzYxODMxMDcsInVzZXJfaWQiOiJVYUJFZDNFVmNoTTYxVHhvWkNReUhJeWZpS2cxIiwic3ViIjoiVWFCRWQzRVZjaE02MVR4b1pDUXlISXlmaUtnMSIsImlhdCI6MTc3NjE4MzEwNywiZXhwIjoxNzc2MTg2NzA3LCJlbWFpbCI6ImFkbWluQHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkbWluQHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.q2jsooZfpmbKT_z-vdMm_IQm5giA5Ln0FrysvqekjCUow8kr1wD_I4ReOuKbNPKxduRh-HKm5zlgoZwh0HSltDTNgvK-6iJ_cIAlO4OiBRaw-DZvMd6bpPdVaTFXgO1kdbA0TzLOQ4zaAeDPodQXmyaPn9ef4kQXaPncSGdvHd_MIxD9-DQ8AftGsqCPs2lzNBrLHEMnd19yTEsl9DKlkAPxW4zAHFqoPMYiVF7L49pIQfjLZXbo2NyGHTMUxLAjCC1HzmC2jBtcE1sI9bTYdOYj6QzMgp-38MfS7onj6neABM2e2frSWfUEZL9qfU5SG_orJuOhEYMQmdDUGikbLQ

###